// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Gets a user by their email.
	//
	//  SELECT
	//      id,
	//      email,
	//      username,
	//      display_name,
	//      password,
	//      created_at,
	//      updated_at
	//  FROM users
	//  WHERE email = $1
	GetUserByEmail(ctx context.Context, db DBTX, email string) (*User, error)
	// Gets a user by their ID.
	//
	//  SELECT
	//      id,
	//      email,
	//      username,
	//      display_name,
	//      password,
	//      created_at,
	//      updated_at
	//  FROM users
	//  WHERE id = $1
	GetUserByID(ctx context.Context, db DBTX, id pgtype.UUID) (*User, error)
	// Gets a user by their username.
	//
	//  SELECT
	//      id,
	//      email,
	//      username,
	//      display_name,
	//      password,
	//      created_at,
	//      updated_at
	//  FROM users
	//  WHERE username = $1
	GetUserByUsername(ctx context.Context, db DBTX, username string) (*User, error)
}

var _ Querier = (*Queries)(nil)
