# Run the sample tests. Requires Meson, Ninja, Gcovr, and a C++ compiler.
test: _assert_installed
    if test -d ./build; then rm -r ./build; fi
    meson setup build -Db_coverage=true
    cd build && meson test
    ninja coverage-xml -C build # writes to build/meson-logs/coverage.xml
    ninja coverage-html -C build # writes to build/meson-logs/coverage.info

# Ensure all required tools are installed.
_assert_installed:
    command -v meson &>/dev/null
    command -v gcovr &>/dev/null
    command -v lcov &>/dev/null
    command -v ninja &>/dev/null
    command -v clang &>/dev/null || command -v gcc &>/dev/null || command -v cc &>/dev/null
