// Package health provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package health

import (
	"github.com/gin-gonic/gin"
)

// Defines values for ErrorResponseError.
const (
	ErrorResponseErrorInternalServerError ErrorResponseError = "InternalServerError"
	ErrorResponseErrorMethodNotAllowed    ErrorResponseError = "MethodNotAllowed"
	ErrorResponseErrorNotFound            ErrorResponseError = "NotFound"
)

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusError HealthResponseStatus = "error"
	HealthResponseStatusOk    HealthResponseStatus = "ok"
)

// ErrorResponse A generic error response
type ErrorResponse struct {
	// Description Human-readable description of the error
	Description *string `json:"description,omitempty"`

	// Error Error code, only somewhat human-readable
	Error ErrorResponseError `json:"error"`
}

// ErrorResponseError Error code, only somewhat human-readable
type ErrorResponseError string

// HealthResponse A response indicating the health of the service.
type HealthResponse struct {
	// Components Each component's health status.
	Components map[string]string `json:"components"`

	// Status The overall health status of the service.
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus The overall health status of the service.
type HealthResponseStatus string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health check
	// (GET /healthz)
	Healthz(c *gin.Context)
	// Metrics
	// (GET /metrics)
	Metrics(c *gin.Context)
	// OpenAPI specification
	// (GET /openapi.json)
	OpenapiJson(c *gin.Context)
	// OpenAPI specification
	// (GET /openapi.yaml)
	OpenapiYaml(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthz(c)
}

// Metrics operation middleware
func (siw *ServerInterfaceWrapper) Metrics(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Metrics(c)
}

// OpenapiJson operation middleware
func (siw *ServerInterfaceWrapper) OpenapiJson(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.OpenapiJson(c)
}

// OpenapiYaml operation middleware
func (siw *ServerInterfaceWrapper) OpenapiYaml(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.OpenapiYaml(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.Healthz)
	router.GET(options.BaseURL+"/metrics", wrapper.Metrics)
	router.GET(options.BaseURL+"/openapi.json", wrapper.OpenapiJson)
	router.GET(options.BaseURL+"/openapi.yaml", wrapper.OpenapiYaml)
}
