services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "cov"
      POSTGRES_PASSWORD: "cov"
      POSTGRES_DB: "cov"
      PGUSER: "cov"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "cov"]
      start_period: 0s
      start_interval: 1s
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: