// This file is auto-generated by @hey-api/openapi-ts

import type {
	Client,
	Options as ClientOptions,
	TDataShape,
} from "@hey-api/client-next";
import { client as _heyApiClient } from "./client.gen";
import type {
	GetV0PingData,
	GetV0PingResponse,
	PostTestData,
	PostTestResponse,
} from "./types.gen";

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

export const postTest = <ThrowOnError extends boolean = false>(
	options: Options<PostTestData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostTestResponse,
		unknown,
		ThrowOnError
	>({
		bodySerializer: null,
		url: "/test",
		...options,
		headers: {
			"Content-Type": "text/plain; charset=utf-8",
			...options?.headers,
		},
	});
};

/**
 * Ping the server and get a pong back with when it processed the request.
 */
export const getV0Ping = <ThrowOnError extends boolean = false>(
	options?: Options<GetV0PingData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetV0PingResponse,
		unknown,
		ThrowOnError
	>({
		url: "/v0/ping",
		...options,
	});
};
