name: Samples - CXX

on:
  push:
    branches:
      - main
    paths:
      - 'samples/c/**'
      - 'samples/cpp/**'
      - '.github/workflows/sample-cxx.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'samples/c/**'
      - 'samples/cpp/**'
      - '.github/workflows/sample-cxx.yml'
  # It is unlikely that we will change this sample very often, hence we want to ensure it continues working.
  schedule:
    - cron: '0 2 5 * *' # every month on the 5th day at midnight 02:00 UTC

permissions: {}

jobs:
  verify:
    strategy:
      matrix:
        lang: [c, cpp]

    name: Build and verify ${{ matrix.lang }} sample
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DIR: samples/${{ matrix.lang }}

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Set up uv
        uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca # v6.0.1
        with:
          # Enable caching ONLY for PRs within the main repo. Forks do not get cache.
          enable-cache: ${{ github.repository == github.event.pull_request.head.repo.full_name }}

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 ninja-build gcc lcov
          uv pip install --user meson gcovr

      - name: Build and test
        run: |
          set -xeuo pipefail
          cd "$DIR"
          uvx meson setup build -Db_coverage=true
          (cd build && uvx meson test)
          ninja coverage -C build # writes to build/meson-logs/coverage.{xml,info}

      - name: Ensure coverage reports exist
        run: |
          set -xeuo pipefail
          cd "$DIR"
          if [ ! -f build/meson-logs/coverage.xml ]; then
            echo "Coverage report not found!"
            exit 1
          fi

          if [ ! -f build/meson-logs/coverage.info ]; then
            echo "Coverage report not found!"
            exit 1
          fi
